<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="IN-SinghPre-1" name="poc.com.testcases.MultipleDataSet" tests="9" failures="1" timestamp="19 May 2020 12:58:58 GMT" time="50.351" errors="0">
  <testcase name="calculator" time="8.105" classname="poc.com.testcases.MultipleDataSet"/>
  <testcase name="calculator" time="6.087" classname="poc.com.testcases.MultipleDataSet"/>
  <testcase name="calculator" time="6.017" classname="poc.com.testcases.MultipleDataSet"/>
  <testcase name="calculator" time="6.041" classname="poc.com.testcases.MultipleDataSet"/>
  <testcase name="calculator" time="6.110" classname="poc.com.testcases.MultipleDataSet"/>
  <testcase name="calculator" time="5.998" classname="poc.com.testcases.MultipleDataSet"/>
  <testcase name="calculator" time="5.949" classname="poc.com.testcases.MultipleDataSet">
    <failure type="java.lang.AssertionError" message="expected [30] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [30] but found [200]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at poc.com.testcases.MultipleDataSet.calculator(MultipleDataSet.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- calculator -->
  <testcase name="calculator" time="6.044" classname="poc.com.testcases.MultipleDataSet"/>
  <testcase name="calculatorMinus" classname="poc.com.testcases.MultipleDataSet">
    <skipped/>
  </testcase> <!-- calculatorMinus -->
</testsuite> <!-- poc.com.testcases.MultipleDataSet -->
